DESC MyTable13;

-- MODIFY COLUMN : 컬럼 타입 변경
ALTER TABLE MyTable13 
MODIFY COLUMN col20 VARCHAR(40);

SELECT * FROM MyTable13;

ALTER TABLE MyTable13
MODIFY COLUMN col13 VARCHAR(40);

-- 연습) MyTable13에서 아무 컬럼이나 타입변경 
ALTER TABLE MyTable13 
MODIFY COLUMN col9 VARCHAR(3);

-- 연습) MyTable08 
